# Generated by Django 5.1.4 on 2025-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_transferdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, default='HSBC Bank', max_length=200, null=True),
        ),
    ]
